---
version: '3.7'

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        env_file:
            - .env

    nginx:
        image: nginx:1.15.3-alpine
        restart: on-failure
        ports:
            - '80:80'
        depends_on:
            - php
        volumes:
            - './public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'


