# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
orbs:
    aws-cli: circleci/aws-cli@0.1.16

jobs:
    build:
        docker:
            - image: circleci/php:7.2-node-browsers

        steps:
            - checkout
            - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
            - run: sudo docker-php-ext-install zip

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      # "composer.lock" can be used if it is committed to the repo
                      - v1-dependencies-{{ checksum "composer.lock" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: composer install -n --prefer-dist

            - save_cache:
                  key: v1-dependencies-{{ checksum "composer.lock" }}
                  paths:
                      - ./vendor

    deploy:
        executor: aws-cli/default
        steps:
            - checkout
            - aws-cli/install
            - aws-cli/setup:
                  profile-name: deployer
                  aws-access-key-id: AWS_ACCESS_KEY_ID
                  aws-secret-access-key: AWS_SECRET_ACCESS_KEY
                  aws-region: AWS_REGION
            - run:
                name: Deploy to EBS
                command: |
                    echo 'export VERSION=$(date "+%d-%m-%y_%H-%M-%S")' >> $BASH_ENV
                    source $BASH_ENV
                    zip ./sourcebundle.zip -r * .[^.]* -x "vendor/*"
                    aws s3 cp sourcebundle.zip s3://elasticbeanstalk-eu-west-2-444397649125/sourcebundle.zip --profile deployer
                    aws elasticbeanstalk create-application-version --application-name blue-green-deployments --version-label $VERSION --source-bundle S3Bucket="elasticbeanstalk-eu-west-2-444397649125",S3Key="sourcebundle.zip" --auto-create-application --profile deployer
                    aws elasticbeanstalk create-environment --application-name blue-green-deployments --environment-name BlueGreenDeployments-blue --version-label $VERSION --solution-stack-name "64bit Amazon Linux 2018.03 v2.8.15 running PHP 7.2" --profile deployer
                    rm -rf ./sourcebundle.zip

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only: master
